# Generated by Django 5.1 on 2024-08-17 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.CharField(max_length=10)),
                ('Humidity', models.CharField(max_length=10)),
                ('Moisture', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realTimeData', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
