# Generated by Django 5.1 on 2024-08-20 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_realtimedata_created_realtimedata_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_pic',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 7, 45, 54, 273733, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='profile_pic',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='realtimedata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 7, 45, 54, 273733, tzinfo=datetime.timezone.utc)),
        ),
    ]
