# Generated by Django 5.1 on 2024-08-20 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_profile_pic_created_profile_pic_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_pic',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 13, 27, 52, 91626, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='realtimedata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 13, 27, 52, 86627, tzinfo=datetime.timezone.utc)),
        ),
    ]
