# Generated by Django 5.1 on 2024-09-06 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_user_created_user_updated_alter_profile_pic_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='aiMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aimessages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
