# Generated by Django 5.1 on 2024-09-07 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_aimessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 8, 50, 58, 859530, tzinfo=datetime.timezone.utc)),
        ),
    ]
