# Generated by Django 5.1 on 2024-09-09 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_aimessages_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='cropSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('Moisture', models.IntegerField()),
                ('Temperature', models.IntegerField()),
                ('Humidity', models.IntegerField()),
                ('Nitrogen', models.IntegerField()),
                ('Phosporous', models.IntegerField()),
                ('Potassium', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='aimessages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 12, 32, 26, 224396, tzinfo=datetime.timezone.utc)),
        ),
    ]
