# Generated by Django 5.1 on 2024-09-09 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_cropspecs_alter_aimessages_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropspecs',
            name='Irrigation_interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cropspecs',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 13, 4, 58, 374908, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='aimessages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 13, 4, 58, 373910, tzinfo=datetime.timezone.utc)),
        ),
    ]
