# Generated by Django 5.1 on 2024-09-09 14:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_cropspecs_description_alter_aimessages_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimessages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 14, 56, 34, 103294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 14, 56, 34, 103294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='arduinoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.IntegerField()),
                ('Humidity', models.IntegerField()),
                ('Moisture', models.IntegerField()),
                ('Nitrogen', models.IntegerField()),
                ('Phosporous', models.IntegerField()),
                ('Potassium', models.IntegerField()),
                ('Irrigation_interval', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 9, 9, 14, 56, 34, 103294, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arduinoData', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
