# Generated by Django 5.1 on 2024-09-11 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_cropspecs_ischosen_alter_aimessages_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimedata',
            name='Nitrogen',
            field=models.IntegerField(default=55),
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='Phosporous',
            field=models.IntegerField(default=33),
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='Potassium',
            field=models.IntegerField(default=47),
        ),
        migrations.AlterField(
            model_name='aimessages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 4, 11, 39, 655656, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='arduinodata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 4, 11, 39, 658653, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 4, 11, 39, 657656, tzinfo=datetime.timezone.utc)),
        ),
    ]
