# Generated by Django 5.1 on 2024-09-16 06:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_realtimedata_nitrogen_realtimedata_phosporous_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='climateLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=100)),
                ('County', models.CharField(max_length=100)),
                ('Sub_county', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='aimessages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 6, 46, 1, 858655, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='arduinodata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 6, 46, 1, 874287, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 6, 46, 1, 874287, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='climateAverageDataPerMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.IntegerField()),
                ('Temperature', models.IntegerField()),
                ('Humidity', models.IntegerField()),
                ('Rainfall_mm', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 9, 16, 6, 46, 1, 874287, tzinfo=datetime.timezone.utc))),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climateLocation', to='backend.climatelocation')),
            ],
        ),
    ]
