# Generated by Django 5.1 on 2024-09-16 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_climatelocation_alter_aimessages_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatelocation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 6, 46, 18, 857433, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='aimessages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 6, 46, 18, 857433, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='arduinodata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 6, 46, 18, 857433, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='climateaveragedatapermonth',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 6, 46, 18, 873057, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 6, 46, 18, 857433, tzinfo=datetime.timezone.utc)),
        ),
    ]
