# Generated by Django 5.1 on 2024-09-22 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_cropspecs_altitude_cropspecs_no_of_irigation_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropspecs',
            name='Irrigation_interval',
        ),
        migrations.AlterField(
            model_name='aimessages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 13, 43, 34, 177266, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='arduinodata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 13, 43, 34, 177266, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='climateaveragedatapermonth',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 13, 43, 34, 177266, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='climatelocation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 13, 43, 34, 177266, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 13, 43, 34, 177266, tzinfo=datetime.timezone.utc)),
        ),
    ]
