# Generated by Django 5.1 on 2024-09-22 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_cropspecs_irrigation_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimessages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 14, 2, 32, 533483, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='arduinodata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 14, 2, 32, 533483, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='climateaveragedatapermonth',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 14, 2, 32, 533483, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='climatelocation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 14, 2, 32, 533483, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='Altitude',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='Humidity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='Moisture',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='Nitrogen',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='No_of_irigation_per_day',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='No_of_irigation_per_week',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='Phosporous',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='Potassium',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='Soil_pH',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='Temperature',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 14, 2, 32, 533483, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='crop_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='description',
            field=models.TextField(default='provide More information about why farmer should plant the crop you specified'),
        ),
    ]
