# Generated by Django 5.1 on 2024-09-23 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_aimessages_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimessages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 6, 8, 32, 194545, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='arduinodata',
            name='Nitrogen',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='arduinodata',
            name='Phosporous',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='arduinodata',
            name='Potassium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='arduinodata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 6, 8, 32, 198539, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='climateaveragedatapermonth',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 6, 8, 32, 200539, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='climatelocation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 6, 8, 32, 199542, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cropspecs',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 6, 8, 32, 196543, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='realtimedata',
            name='Humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='realtimedata',
            name='Moisture',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='realtimedata',
            name='Nitrogen',
            field=models.FloatField(default=55),
        ),
        migrations.AlterField(
            model_name='realtimedata',
            name='Phosporous',
            field=models.FloatField(default=33),
        ),
        migrations.AlterField(
            model_name='realtimedata',
            name='Potassium',
            field=models.FloatField(default=47),
        ),
    ]
